spring:
  application:
    name: trade-gateway-service
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  
  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 30s
        pool:
          type: ELASTIC
          max-connections: 200
          max-idle-time: 20s
          max-life-time: 60s
          evict-in-background: true
        compression: true
      forward-headers-strategy: native
      routes:
        - id: trade-ingress-trades-post
          uri: ${GATEWAY_TRADE_INGRESS_URL}
          predicates:
            - Path=${GATEWAY_PATH_TRADES:/api/trades}
            - Method=POST
#          filters:
#            - StripPrefix=0
#            - name: RequestRateLimiter
#              args:
#                redis-rate-limiter.replenishRate: ${RATE_LIMIT_REPLENISH_RATE}
#                redis-rate-limiter.burstCapacity: ${RATE_LIMIT_BURST_CAPACITY}
#                redis-rate-limiter.requestedTokens: 1
#                key-resolver: "#{@ipKeyResolver}"
        - id: trade-ingress-trades
          uri: ${GATEWAY_TRADE_INGRESS_URL}
          predicates:
            - Path=${GATEWAY_PATH_TRADES:/api/trades}/**
          filters:
            - StripPrefix=0
        
        - id: trade-ingress-cache
          uri: ${GATEWAY_TRADE_INGRESS_URL}
          predicates:
            - Path=${GATEWAY_PATH_TRADES_CACHE:/api/trades/cache}/**
          filters:
            - StripPrefix=0
        
        - id: trade-ingress-audit
          uri: ${GATEWAY_TRADE_INGRESS_URL}
          predicates:
            - Path=${GATEWAY_PATH_AUDIT:/api/audit}/**
          filters:
            - StripPrefix=0
    discovery:
      client:
        composite-indicator:
          enabled: false
        health-indicator:
          enabled: false
        
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout: 2000ms

server:
  port: ${GATEWAY_PORT:8085}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: always
  health:
    redis:
      enabled: true

logging:
  level:
    root: WARN
    org.springframework.cloud.gateway: WARN
    org.springframework.web: WARN
    org.springframework.boot: WARN
    com.tradeplatform: INFO
    com.tradeplatform.tradegateway: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

