spring:
  application:
    name: trade-service
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

server:
  port: ${BACKEND_PORT}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.tradeplatform: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

