spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:trade_db}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
  
  data:
    mongodb:
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      database: ${MONGO_DATABASE}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      authentication-database: ${MONGO_AUTH_DB}
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: tradeEvent:com.tradeplatform.tradeservice.kafka.TradeEvent
    consumer:
      group-id: trade-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.type.mapping: tradeEvent:com.tradeplatform.tradeservice.kafka.TradeEvent
        spring.json.trusted.packages: "*"

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

trade:
  kafka:
    topics:
      trade-reports: ${KAFKA_TOPIC_TRADE_REPORTS}
  
  vector-db:
    host: ${VECTOR_DB_HOST}
    port: ${VECTOR_DB_PORT}
    collection: ${VECTOR_DB_COLLECTION}
  
  cache:
    ttl:
      trade-latest: 30
      dashboard-summary: 10
      dashboard-by-book: 10
      dashboard-by-counterparty: 10
  
  scheduler:
    expiration:
      cron: ${TRADE_EXPIRATION_CRON:0 0 * * * ?} # default: every hour at the top of the hour
        #  * Common cron examples:
        #  * - "0 0 * * * ?" - Every hour
        #  * - "0 */5 * * * ?" - Every 5 minutes (NOTE: use */5 not */05)
        #  * - "0 */30 * * * ?" - Every 30 minutes
        #  * - "0 0 0 * * ?" - Every day at midnight
        #  * - "0 0 0 * * MON" - Every Monday at midnight